// File generated by FlutterFire CLI & configured for Transwallet.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDszYeX3ebthRAvclvxxb5Yh-GDWJQYlxs',
    appId: '1:693939451746:web:56f0bd8a216df0f1e09e3b',
    messagingSenderId: '693939451746',
    projectId: 'transwallet-b6b93',
    authDomain: 'transwallet-b6b93.firebaseapp.com',
    storageBucket: 'transwallet-b6b93.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDszYeX3ebthRAvclvxxb5Yh-GDWJQYlxs',
    appId: '1:693939451746:android:56f0bd8a216df0f1e09e3b',
    messagingSenderId: '693939451746',
    projectId: 'transwallet-b6b93',
    storageBucket: 'transwallet-b6b93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDszYeX3ebthRAvclvxxb5Yh-GDWJQYlxs',
    appId: '1:693939451746:ios:56f0bd8a216df0f1e09e3b',
    messagingSenderId: '693939451746',
    projectId: 'transwallet-b6b93',
    storageBucket: 'transwallet-b6b93.firebasestorage.app',
    iosBundleId: 'com.trans.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDszYeX3ebthRAvclvxxb5Yh-GDWJQYlxs',
    appId: '1:693939451746:ios:56f0bd8a216df0f1e09e3b',
    messagingSenderId: '693939451746',
    projectId: 'transwallet-b6b93',
    storageBucket: 'transwallet-b6b93.firebasestorage.app',
    iosBundleId: 'com.trans.wallet',
  );
}
